version: "3.8"

services:

    node-1:
        image: anatolydudko/blockchain-cryptocurrency:latest
        container_name: node-1
        build: .
        ports:
            - "5001:5000"
        networks:
            - cluster

    node-2:
        image: anatolydudko/blockchain-cryptocurrency:latest
        container_name: node-2
        build: .
        ports:
            - "5002:5000"
        networks:
            - cluster

    node-3:
        image: anatolydudko/blockchain-cryptocurrency:latest
        container_name: node-3
        build: .
        ports:
            - "5003:5000"
        networks:
            - cluster

networks:
    cluster:
        driver: bridge
