from time import time

from src.utils.printable import Printable


class Block(Printable):
    """ A single block of blockchain.
    :argument index: The index of this block.
    :argument previous_hash: The hash of the previous block in the blockchain.
    :argument transactions: A list of transaction which are included in the block.
    :argument proof: The proof of work number that yielded this block.
    :argument timestamp: The timestamp of the block (automatically generated by default).
    """

    def __init__(self, index, previous_hash, transactions, proof, timestamp=None):
        self.index = index
        self.previous_hash = previous_hash
        self.transactions = transactions
        self.proof = proof
        self.timestamp = time() if timestamp is None else timestamp
